services:
  authorization-server:
    build: ./auth-server
    ports:
      - "8081:8080"
    networks:
      - my_network

  resource-server:
    build: ./resource-server
    ports:
      - "8082:8080"
    networks:
      - my_network



networks:
  my_network:
    driver: bridge
