version: '3.8'
services:
  authorization-server:
    build: ./auth-server
    ports:
      - "8081:8080"

  resource-server:
    build: ./resource-server
    ports:
      - "8082:8080"

  client-app:
    build: ./client-app
    ports:
      - "8083:8080"

